### ISSUE TITLE
Replace filename and folder choice with info from pipe

### ISSUE THREAD

**Issue by pmanko** [pmanko/MXPTiny#4]

**Comment by pmanko** [comment]
@philliha I'm not sure exactly how to translate your pipe code into C++. This project uses pipes as well, and it might be simpler to use them in the same way - using the CreateNamedPipe() family of functions. 

Here are some references so I don't lose them:

1. Pipe functions: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365146(v=vs.85).aspx
2. multithread pipe example in c++: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365588(v=vs.85).aspx
3. relevant question: http://stackoverflow.com/questions/1906561/communication-between-c-and-c-sharp-through-pipe
4. Pipe Streams (which seem to be one level up from the pipe functions): https://msdn.microsoft.com/en-us/library/system.io.pipes.namedpipeserverstream(v=vs.110).aspx

The last resource has code examples, but mentions this for c++: "No code example is currently available or this language may not be supported." I'm worried this suggests it might be easier to use the approach from the second resource in c++.

**Comment by pmanko** [comment]
Another example: https://msdn.microsoft.com/en-us/library/bb546085(v=vs.110).aspx

**Comment by pmanko** [comment]
Quick tutorial: http://avidinsight.uk/2012/03/introduction-to-win32-named-pipes-cpp/

**Comment by pmanko** [comment]
From the path that gets sent (ex. "Pc:\\vidwork\\3787A.AVI"), change the extension to .ts. 

Message summary:

INIT
P --> start recording: create a new ts file using the sent path
stop --> stop recording, convert to mp4, delete ts file
halt --> Logger might change, pipes will change: close pipes

**Comment by philliha** [comment]
Your code works fine with a halt currently  👍

**Comment by philliha** [comment]
`STARTUPINFOW si;
		PROCESS_INFORMATION pi;

		memset(&si, 0, sizeof(si));
		si.cb = sizeof(si);
		ZeroMemory(&pi, sizeof(pi));
//c:\\users\\mike\\documents\\decklink.ts becomes ts file from mike
//c:\\vidwork\\tempa.mp4 becomes file from mike.mp4
		TCHAR cmd[] = _T("c:\\bats99\\ffmpeg2 -i c:\\users\\mike\\documents\\decklink.ts -bsf:a aac_adtstoasc -acodec copy -vcodec copy c:\\vidwork\\tempa.mp4 -y");
//runs cmd process in background
		if (CreateProcess(NULL, cmd, NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, NULL, &si, &pi))
		{
			WaitForSingleObject(pi.hProcess, INFINITE);
			CloseHandle(pi.hProcess);
			CloseHandle(pi.hThread);
		}
//all become appropriate file name
		if (rename("c:\\vidwork\\tempa.mp4", "c:\\vidwork\\tempa.avi") != 0) {
			remove("c:\\vidwork\\tempa.avi");
			rename("c:\\vidwork\\tempa.mp4", "c:\\vidwork\\tempa.avi");
		}
		remove("c:\\users\\mike\\documents\\decklink.ts");`
